### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by nickkobis** [cse442-fall-2019-offering/442projects-knot_kahoot#1]
As a program manager, when I open the app, the login Screen loads up so I can log in.

**Comment by nickkobis** [comment]
Acceptance Test
(1) type in not_kahoot.com
(2)see text with login with user name and password

**Comment by shreyavp** [comment]
Acceptance test:

Allows user to enter text for username and password. 
(1) Enter a username and password in the corresponding text box on login page
(2) Navigate to login by clicking on Login on the navbar

The test passes
