### ISSUE TITLE
TASK-Google login and authentication

### ISSUE THREAD

**Issue by nickkobis** [cse442-fall-2019-offering/442projects-knot_kahoot#49]

**Comment by haemanthisree** [comment]
Task Test:
1) Goto Website URL "http://localhost:8080/'
2) Click "Sign in with Google"
3) Enter not.kahoot@gmail.com in username
3) Enter pls*dont?hack&us in password
4) Click next
5) The screen should say 'Logged in as not.kahoot@gmail.com' and 'Logout'
