### ISSUE TITLE
STORY - Base generate functionality

### ISSUE THREAD

**Issue by nickkobis** [cse442-fall-2019-offering/442projects-knot_kahoot#61]
As a program manager, i would like to input just the days and teams and have the schedule just generate practices, so I can have an Idea what the final product would look like.

**Comment by haemanthisree** [comment]
Acceptance Test:
1) Go to the create page
2) Click on the team button
3) Add a team named A and a team named B 
4) Click on the event button 
5) Add Monday and Wednesday
6) Click on Submit Data 
7) Go to the web inspector 
8) The corresponding team with practice day will be printed on the console
