### ISSUE TITLE
TASK - Output post algorithm Structure 

### ISSUE THREAD

**Issue by nickkobis** [cse442-fall-2019-offering/442projects-knot_kahoot#63]
when the algorithm is ran, the program will take the final data structure and covert it into a String

**Comment by haemanthisree** [comment]
Task Test:
1) Go to create page. 
2) Add a team named A and a team named B.
3) Add an event on Monday and Wednesday.
4) click on submit data.
5) The corresponding day and team will be printed in the console of the inspector.
