### ISSUE TITLE
STORY - Time-Slot pop-up

### ISSUE THREAD

**Issue by Gitanjali2016** [cse442-fall-2019-offering/442projects-knot_kahoot#72]
As a program manager, when I click on the add Time-Slot button, I would like to select a day and time slot between 9am and 5pm, and click submit then close so that I can see it on the create page when the pop-up is closed

**Comment by haemanthisree** [comment]
Acceptance Test:
1.On the create page, click on the time slot button on the left. A pop up will appear.
2. Select a day and time slot and hit the submit button. 
3. Hit the close button
4. The pop up disappears and the The selected day and time slot will show up under the time slot column on Create Page

**Comment by haemanthisree** [comment]
https://github.com/cse442-fall-2019-offering/442projects-knot_kahoot/pull/92
