### ISSUE TITLE
STORY - Team pop-up

### ISSUE THREAD

**Issue by Gitanjali2016** [cse442-fall-2019-offering/442projects-knot_kahoot#73]
As a program manager, when I click on the team button, I would like to be able to enter a team name and submit it so that I could see all teams for scheduling practices and games.

**Comment by haemanthisree** [comment]
Acceptance Test:
1)Go to the Create Page
2) Click on the Team button 
3) Enter a Team Name
4) Click the submit button. Click the close button.
5) The pop up closes 
6) The team name will reflect under the teams on the pop up page
