### ISSUE TITLE
STORY - Options pop-up

### ISSUE THREAD

**Issue by Gitanjali2016** [cse442-fall-2019-offering/442projects-knot_kahoot#74]
As a program manager, I would like to click on the options button so that I can select the number of weeks the practice schedule for teams repeats itself, given a start date.

**Comment by haemanthisree** [comment]
Acceptance Test:
1) Go to the Create Page
2) Click on the Options button
3) Enter Number of weeks and pick a date from the calendar for the Start Date. 
4) Hit the submit button 
5) Hit the Close button 
6)The pop up closes

**Comment by haemanthisree** [comment]
https://github.com/cse442-fall-2019-offering/442projects-knot_kahoot/pull/92
