### ISSUE TITLE
STORY - Server

### ISSUE THREAD

**Issue by Gitanjali2016** [cse442-fall-2019-offering/442projects-knot_kahoot#76]
As a program manager, I would like to go to https://www-student.cse.buffalo.edu/CSE442-542/2019-Fall/cse-442h/frontend so that I could login and use the app.

**Comment by shanegri** [comment]
Acceptance test:
1) goto https://www-student.cse.buffalo.edu/CSE442-542/2019-Fall/cse-442h/frontend
2) Sign in with google account - username: not.kahoot@gmail.com, password: pls*dont?hack&us 
3) No errors should occur

**Comment by shanegri** [comment]
https://github.com/cse442-fall-2019-offering/442projects-knot_kahoot/commit/7337d5ed4df02eeb9ee1f262a894bcb1524e228b
