### ISSUE TITLE
STORY- Generate Schedule

### ISSUE THREAD

**Issue by nickkobis** [cse442-fall-2019-offering/442projects-knot_kahoot#77]
As a program manager, I want to be able to add teams, time slots (days and times) and options(start date and number of weeks) so that when I click the submit data button,a schedule will be created.

**Comment by haemanthisree** [comment]
https://github.com/cse442-fall-2019-offering/442projects-knot_kahoot/pull/98

**Comment by haemanthisree** [comment]
Acceptance Test:
1. Login to the application
2. Go to the Create Page 
3. Click on the team button
4. Add a team called "Team 1"
5. Click on the team button
5. Add a team called "Team 2"
6. Click on the time slot button
7. Select Monday and 10AM and hit the submit button
8. Select Wednesday and 11AM and hit the submit button
9.Select Thursday and 04PM and hit the submit button
10.Click the close button. 
11.The teams and days with time slots will reflect on the create page 
11. Click on the options button on the create page and enter the number of weeks and select a start date and hit the submit button. 
13. On the create page, click on the 'Submit Data' button.
14. The schedule will be on the Schedules Page.
