### ISSUE TITLE
TASK - impossible checker

### ISSUE THREAD

**Issue by nickkobis** [cse442-fall-2019-offering/442projects-knot_kahoot#83]
This is to check if an impossible case cannot be scheduled. See tests for more details

**Comment by haemanthisree** [comment]
Task Test:
1. Go to the create page
2. Click on the Team button
3. Create a team named A and hit the submit button
4. Create a team named B and hit the submit button
5. Create a team named C and hit the submit button
6. Hit the close button
7. Click on the time slot button
8. Select Monday and 09:00AM for the time and hit submit 
9.Select Tuesday and 10:00AM for the time and hit submit 
10. Click the close button
11. Click submit data 
12. An error message saying "The minimum number of time slots you need given 3 teams is 4. You currently have 2 time slots given. Please add more time slots".
